"""IM Cli Adapter mixin 共享基类（F9 类型治理）。

共享基类仅做类型声明（方法裸参数 stub + 状态 Any），集中声明跨 mixin 交叉
成员；无 __init__、无方法体，运行时代入 MRO 由组合类/各 mixin 真实赋值与实现，
零行为影响。惰性注解，运行时仅依赖 LinkoraComponentBase（无循环导入）。
"""
from __future__ import annotations

from typing import Any

from src.im_adapter.base_adapter import BaseIMAdapter


class IMAdapterBase(BaseIMAdapter):
    # === 内部状态（组合类 / 各 mixin __init__ 赋值；精确类型见赋值点） ===

    # === 跨 mixin 方法（真实签名原样；实现在各自 mixin） ===
    def _detect_and_rename(self, path) -> Any: ...
    def _doc_read_fallback(self, node_id, entity_type) -> Any: ...
    def _extract_text_from_file(self, path) -> Any: ...
    @staticmethod
    def _generate_video_cover(video_path) -> Any: ...
    @staticmethod
    def _infer_media_flag(ref) -> Any: ...
    @staticmethod
    def _infer_resource_type(media_id) -> Any: ...
    def _run_cli_file(self, args, tmpdir, output_base) -> Any: ...
    def _unwrap_wiki_file_token(self, meta) -> Any: ...
    def chat_message_list_all(self, start, end, limit, max_pages, extra_chat_ids, chat_ids, chat_meta) -> Any: ...
    def doc_list(self, folder_token, page_size, page_token) -> Any: ...
    def doc_read(self, node_id, content_format, entity_type) -> Any: ...
    def doc_search(self, query, page_size) -> Any: ...
    def download_media(self, *, media_id, message_id, conversation_id, output_path) -> Any: ...
    def media_upload(self, file_path, media_type) -> Any: ...
    def _normalize_message(self, msg) -> Any: ...
